- alias: 00_start
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:  
    - service: mqtt.publish
      data_template:
         topic: "notification/info"
         payload_template: '041'
         retain: true
      
- alias: 00_backup_everyday
  initial_state: true
  trigger:
    - platform: time
      at: '05:00:00'
  action:
    - service: script.turn_on
      entity_id: script.ha_backup