# Управление ночным режимы камеры 
- alias: 08_da_xiaofang
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - sensor.illumination_f0b429cc1f11
  action:
    service_template: >-
      {% set illum = states('sensor.illumination_f0b429cc1f11') | float %}
      {% if illum >= 200 %}
        switch.turn_off
      {% elif illum < 200 %}
        switch.turn_on
      {% endif %}
    entity_id: switch.xiaofang1s_night_mode
    
